### ISSUE TITLE
Question: Documentation or examples for manifest generation?

### ISSUE THREAD

**Issue by mobleyt** [dbmdz/iiif-server-hymir#18]
Sorry, more of a question here. I see that you mention 'highly customizable manifest generation' in the README. Are there any docs or examples I could follow for that? 

I have an installation running and have set up a simple file resolver rule for the Image API with a sample image, and that is working fine. However, I don't see how to generate/access a manifest for said item via the Presentation API. 

If I've misunderstood and Hymir doesn't actually generate manifests so much as present those already created, please set me straight! Thanks for your time.

**Comment by jbaiter** [comment]
> If I've misunderstood and Hymir doesn't actually generate manifests so much as present those already created, please set me straight! Thanks for your time.

Yep, that's right, we currently only include a filesystem-based implementation that loads existing Manifests. We can't really offer any other implementations, since it's always highly specific to the IIIF implementor's environment.

But if you have some Manifest generation code that you want to hook up, you can just implement the [`PresentationRepository`](https://github.com/dbmdz/iiif-server-hymir/blob/master/src/main/java/de/digitalcollections/iiif/hymir/presentation/backend/api/PresentationRepository.java) interface and make it available to the Spring environment (e.g. annotate your implementation with `@Repository` and include it in your configuration's `@ComponentScan`).

**Comment by mobleyt** [comment]
Ah, understood. Thanks for the clarification!
